name: 'Commit tagger'
description: 'Tag commit with a given version'
author: 'Thiago Vaz Dias'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  tag:
    description: 'Tag text'
    default: '0.1.0'
  commit-sha:
    description: optional commit sha to apply the tag to
  when-tag-exists:
    description: action to take when the tag already exists (fail, skip, overwrite)
    default: fail
runs:
  using: 'node12'
  main: 'lib/main.js'
